
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 05 07:03:02 CST 2018
//----------------------------------------------------

package cometmach;

/** CUP generated class containing symbol constants. */
public class CometMachSymbols {
  /* terminals */
  public static final int tSymbol = 32;
  public static final int tFor = 16;
  public static final int tAnd = 7;
  public static final int tEndSentence = 42;
  public static final int tMain = 21;
  public static final int tDiv = 41;
  public static final int tDefault = 15;
  public static final int tTrue = 2;
  public static final int tParClose = 18;
  public static final int tBoxAssing = 24;
  public static final int tMulti = 40;
  public static final int tNumberI = 44;
  public static final int tVoid = 26;
  public static final int tAdd = 38;
  public static final int tClose = 14;
  public static final int tNumberD = 45;
  public static final int tFalse = 3;
  public static final int tComparative = 8;
  public static final int tElse = 10;
  public static final int tParOpen = 17;
  public static final int EOF = 0;
  public static final int tBox = 23;
  public static final int tElseif = 9;
  public static final int tSentence = 43;
  public static final int error = 1;
  public static final int tIs = 12;
  public static final int tThen = 13;
  public static final int tOr = 6;
  public static final int tAssign = 5;
  public static final int tStapleOpen = 35;
  public static final int tInteger = 29;
  public static final int tIf = 4;
  public static final int tEnd = 20;
  public static final int tId = 34;
  public static final int tReturn = 27;
  public static final int tSwap = 11;
  public static final int tSub = 39;
  public static final int tChar = 46;
  public static final int tCicle = 22;
  public static final int tWord = 31;
  public static final int tComma = 37;
  public static final int tStapleClose = 36;
  public static final int tBoolean = 33;
  public static final int tDecimal = 30;
  public static final int tFunction = 25;
  public static final int tTo = 19;
  public static final int tInit = 28;
}

